{% set version = "202107.1047" %}

package:
  name: lib3to6
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/lib3to6/lib3to6-{{ version }}.tar.gz
  sha256: 022db330b42a056a0f09207a0740445d029444890c69e20582ef99ae27acb717

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - lib3to6 = lib3to6.__main__:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - astor
    - click <8.0  # [py<36]
    - pathlib2
    - typing   # [py<35]
    - wheel

test:
  imports:
    - lib3to6

about:
  home: https://github.com/mbarkhau/lib3to6
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Compile Python 3.6+ code to Python 2.7

extra:
  recipe-maintainers:
    - raybellwaves
